### ISSUE TITLE
Lua error when right clicking on player

### ISSUE THREAD

**Issue by secured** [freebaser/oUF_Freebgrid#4]
Date: 2013-03-25 20:03:13
ID: 1
Error occured in: Global
Count: 1
Message: ..\FrameXML\UnitPopup.lua line 940:
   Usage: GetRaidRosterInfo(index)
Debug:

   ..\FrameXML\UnitPopup.lua:940: UnitPopup_HideButtons()
   ..\FrameXML\UnitPopup.lua:267:
      ..\FrameXML\UnitPopup.lua:248

   ..\FrameXML\SecureTemplates.lua:239: initFunction()
   ..\FrameXML\UIDropDownMenu.lua:69: UIDropDownMenu_Initialize()
   ..\FrameXML\UIDropDownMenu.lua:864: ToggleDropDownMenu()
   ..\FrameXML\SecureTemplates.lua:310: handler()
   ..\FrameXML\SecureTemplates.lua:632: SecureActionButton_OnClick()
   ..\FrameXML\SecureTemplates.lua:672:
      ..\FrameXML\SecureTemplates.lua:664

**Comment by freebaser** [comment]
https://github.com/haste/oUF/issues/182

Waiting to see how this is resolved.
